id = "sentry-mcp"
name = "Sentry MCP Server"
description = "Model Context Protocol Server for Sentry"
version = "0.1.1"
schema_version = 1
authors = ["fabric0de <junghyeonkim.dev@gmail.com>"]
repository = "https://github.com/fabric0de/sentry-mcp-server-zed"
themes = []
icon_themes = []
languages = []
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[context_servers.sentry-mcp]
name = "Sentry MCP Server"
